### ISSUE TITLE
Не правильно вычисляется значение

### ISSUE THREAD

**Issue by Anatoliyphp** [adelsibga/BackEnd#2]
![image](https://user-images.githubusercontent.com/61590293/162758615-d5b9709c-ffbd-435e-867d-deb5b98b3cba.png)

**Comment by adelsibga** [comment]
![image](https://user-images.githubusercontent.com/79917869/163041807-89b5d121-17eb-4edf-8ce4-d15287e76b92.png)
![image](https://user-images.githubusercontent.com/79917869/163041908-21ebc456-cb9c-4cdb-9451-9fba5b4ed44d.png)
У меня все корректно обрабатывается

**Comment by Anatoliyphp** [comment]
![image](https://user-images.githubusercontent.com/61590293/163329206-8210c43b-0b4d-4990-9e9c-0417e70702ca.png)
Проблема все-таки есть, при вводе чисел с плавающей запятой. Если ты у себя введешь 9.9 / 5 у тебя тоже сломается. Нужно это как-то обработать: либо вывести ошибку, либо отдельно приводить такие числа.

**Comment by adelsibga** [comment]
Я не могу ввести точку «.» считается как не число и просит ввести ещё раз. Одногруппник проверял и у него также. Я просто не вижу проблему. Может из-за разницы Visual Studio? У меня 2022

**Comment by adelsibga** [comment]
Понять бы причину такой ошибки

**Comment by Anatoliyphp** [comment]
> Я не могу ввести точку «.» считается как не число и просит ввести ещё раз. Одногруппник проверял и у него также. Я просто не вижу проблему. Может из-за разницы Visual Studio? У меня 2022

Если действительно так, значит у моей винды в этом плане какие-то проблемы, проверю еще раз с русской и закрою, если все норм
